<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\EntityRepository;

/**
 * DonatorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonatorsRepository extends EntityRepository
{
    public function getDonationsLastMonth($from, $to)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('e')
            ->from('AppBundle:Donators', 'e')
            ->where('e.createdAt BETWEEN :firstDate AND :lastDate')
            ->setParameter('firstDate', $from)
            ->setParameter('lastDate', $to);

        $result = $qb->getQuery()->getResult();
        return $result;
    }

    public function getDonationsByDay()
    {
        $em = $this->getEntityManager();

        $RAW_QUERY = 'SELECT DATE(created_at),
             SUM(amount)
             FROM donators
             GROUP BY DATE(created_at);';

        $statement = $em->getConnection()->prepare($RAW_QUERY);
        $statement->execute();

        return $statement->fetchAll();
    }
}
