<?php

namespace AppBundle\Repository;

/**
 * DonatorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonatorsRepository extends \Doctrine\ORM\EntityRepository
{
}
